name: Update File on Push

on: [push]

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update file
        run: |
          cat > install.sh << EOF
          #!/bin/bash
          case \$(basename "\\$SHELL") in
            "bash")
              target=".bashrc"
              ;;
            "zsh")
              target=".zshrc"
              ;;
            *)
              exit 1
              ;;
          esac

          if [ -f "\\$HOME/\\$target" ]; then
            awk '\\$NF != "#--rcHorse--" {print \\$0}' "\\$HOME/\\$target" > temp_file && mv temp_file "\\$HOME/\\$target"
          fi

          echo "$(while IFS= read -r line; do echo "$line #--rcHorse--"; done < rcHorse.sh)" >> "\\$HOME/\\$target"
          EOF
          
          chmod +x install.sh
          
      - name: Commit and push changes
        uses: test-room-7/action-update-file@v1
        with:
          file-path: install.sh
          commit-msg: "Update install.sh"
          github-token: ${{ secrets.GITHUB_TOKEN }}
